### ISSUE TITLE
Keywords and symbols are expected to have quotes

### ISSUE THREAD

**Issue by MartinPetkov** [Adjective-Object/488-lang#1]
The keywords and symbols shouldn't have quotes, since the specification is only using them as metanotation to distinguish them. This should be corrected by removing the quotes around some of the match regexes.

**Comment by Adjective-Object** [comment]
Oh, thanks for pointing that out! This should be addressed by commit 5cffe70d2be9533f6817a95e3e43ee1d227b8db5
